config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'
  devise_for :users
  get "posts/index"
  resources :events

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :user
    validate :expiration_date_cannot_be_in_the_past?
    validates :name, presence: { message: "El Nombre del evento es obligatorio." }
    validates :description, presence: { message: "La Descripción del evento es obligatoria." }
    validates :location, presence: { message: "La ubicación del evento es obligatoria." }
    validates :capacity, presence: { message: "La capacidad del evento no puede ser inferior a 1." }


    def expiration_date_cannot_be_in_the_past?
        if date.present? && date < Date.today
          errors.add(:date, "La fecha del evento no puede ser inferior a hoy. ")
        end
        if !date.present?
            errors.add(:date, "Debe ingresar una fecha.")
        end
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :events
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

     before_action :configure_permitted_parameters, if: :devise_controller?
     before_action :set_maps_key

     protected

          def configure_permitted_parameters
               devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :age, :email, :password, :current_password)}
          end

          def set_maps_key
               @maps_key = Rails.application.credentials[:MAPS_API_KEY]
          end



end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  def index
    @events = current_user.events.group_by_month(:date, format: "%b %Y").count
    @lastEvents = current_user.events.order(date: :asc).limit(5)
    print(@lastEvents)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!

  # GET /events or /events.json
  def index
    @events = current_user.events.where(:user_id => current_user.id)
  end

  # GET /events/1 or /events/1.json
  def show
    @event = current_user.events.find(params[:id])
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
    @event = current_user.events.find(params[:id])
  end

  # POST /events or /events.json
  def create
    @event = Event.new(event_params)
    @event.user_id = current_user.id

    respond_to do |format|
      if @event.save
        format.html { redirect_to event_url(@event), notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    @event = Event.find(params[:id])
      respond_to do |format|
        if @event.user_id == current_user.id
          if @event.update(event_params)
            format.html { redirect_to event_url(@event), notice: "Event was successfully updated." }
            format.json { render :show, status: :ok, location: @event }
          else
            format.html { render :edit, status: :unprocessable_entity }
            format.json { render json: @event.errors, status: :unprocessable_entity }
          end
        else
          format.html { redirect_to destroy_user_session_path, notice: "No puedes editar este evento" }
        end
      end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event = Event.find(params[:id])
      @event.destroy!
      respond_to do |format|
        if @event.user_id == current_user.id
          @event.destroy!
          format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
          format.json { head :no_content }
        else
          format.html { redirect_to destroy_user_session_path, notice: "No puedes editar este evento" }
        end
      end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:name, :description, :date, :location, :capacity, :latitude, :longitude)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/dashboard/index.html.erb
<br><br>
<div class="row">
  <div class="col-lg-6">
    <div class="card" style="padding: 20px">
      <h1>Eventos por mes</h1>
        <%= column_chart @events %>
    </div>
  </div>
  <div class="col-lg-6">
    <div class="card" style="padding: 20px">
      <h1>Próximos 5 eventos</h1>
      <table class="table">
        <thead>
          <tr>
            <th>Nombre</th>
            <th>Fecha</th>
            <th>Ubicación</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @lastEvents.each do |event| %>
          <tr>
            <td><%= event.name %></td>
            <td><%= event.date.strftime('%d/%m/%Y %H:%M') %></td>
            <td><%= event.location %></td>
            <td><%= link_to "Detalle Evento", event_path(event), class: 'btn btn-primary' %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/events/_event.html.erb
<div id="<%= dom_id event %>">
  <p>
    <strong>Name:</strong>
    <%= event.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= event.description %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= event.date %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= event.location %>
  </p>

  <p>
    <strong>Capacity:</strong>
    <%= event.capacity %>
  </p>

</div>

app/views/events/_form.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="card p-5">
      <%= form_with model: event, local: true, data: {
                                            controller: :maps,
                                            action: "google-maps-callback@window->maps#initializeMap"
                                          } do |form| %>
        <% if event.errors.any? %>
          <div style="color: red">
            <h2><%= pluralize(event.errors.count, "error") %> en el formulario:</h2>

            <ul>
              <% event.errors.each do |error| %>
                <li><%= error.message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
          <%= form.label :name, "Nombre", style: "display: block" %>
          <%= form.text_field :name, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= form.label :description, "Descripción", style: "display: block" %>
          <%= form.text_area :description, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= form.label :date, "Fecha de evento", style: "display: block" %>
          <%= form.datetime_field :date, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= form.label :location, "Ubicación", style: "display: block" %>
          <%= form.text_field :location, class: "form-control", data: { target: "maps.field", action: "keydown->maps#preventSubmit" } %>
        </div>

        <%= form.hidden_field :latitude, class: 'form-control', data: { target: "maps.latitude" } %>
        <%= form.hidden_field :longitude, class: 'form-control', data: { target: "maps.longitude" } %>

        <%= content_tag :div, nil, data: { target: "maps.map" }%>

        <div class="form-group">
          <%= form.label :capacity, "Capacidad", style: "display: block" %>
          <%= form.number_field :capacity, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= form.submit "Enviar", class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/events/edit.html.erb
<h1>Editar Evento</h1>

<%= render "form", event: @event %>

app/views/events/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Lista de Eventos</h1>
<a href="<%= new_event_path %>" class="btn btn-success btn-icon-split">
  <span class="text">Crear Evento</span>
</a>
<br><br>
<table class="table">
  <thead>
    <tr>
      <th>Id</th>
      <th>Nombre</th>
      <th>Fecha</th>
      <th>Ubicación</th>
      <th>Capacidad</th>
      <th></th>
  </thead>
  <tbody>
    <% @events.each do |event| %>
    <tr>
      <td><%= event.id %></td>
      <td><%= event.name %></td>
      <td><%= event.date.strftime('%d/%m/%Y %H:%M') %></td>
      <td><%= event.location %></td>
      <td><%= event.capacity %></td>
      <td><%= link_to "Detalle Evento", event_path(event), class: 'btn btn-primary' %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/events/new.html.erb
<h1>Nuevo evento</h1>

<%= render "form", event: @event %>

app/views/events/show.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1>Detalles del producto</h1>
    <%= link_to "Editar", edit_event_path(@event), class: 'btn btn-warning' %>
    <%= link_to 'Eliminar', event_path(@event),
  data: {turbo_method: :delete}, class: 'btn btn-danger' %>
  <br><br>
    <div class="card" style="padding: 20px;">
      <table class="table">
        <tr>
          <td><b>Nombre del evento:</b></td>
          <td><%= @event.name %></td>
        </tr>
        <tr>
          <td><b>Fecha evento:</b></td>
          <td><%= @event.date.strftime('%d/%m/%Y %H:%M') %></td>
        </tr>
        <tr>
          <td><b>Capacidad</b></td>
          <td><%= @event.capacity %></td>
        </tr>
        <tr>
          <td><b>Descripción:</b></td>
          <td><%= @event.description %></td>
        </tr>
        <tr>
          <td><b>Fecha de creación:</b></td>
          <td><%= @event.created_at.strftime('%d/%m/%Y %H:%M') %></td>
        </tr>
        <tr>
          <td><b>Fecha de actualización:</b></td>
          <td><%= @event.updated_at.strftime('%d/%m/%Y %H:%M') %></td>
        </tr>
        <tr>
          <td><b>Ubicación:</b></td>
          <td><%= @event.location %></td>
        </tr>
        <tr>
          <td></td>
          <td>
            <%= image_tag "https://maps.googleapis.com/maps/api/staticmap?zoom=15&size=400x300&center=#{@event.latitude},#{@event.longitude}&markers=#{@event.latitude},#{@event.longitude}&key=#{@maps_key}", alt: "Map", class: 'map' %>
          </td>
        </tr>
      </table>
    </div>
  </div>
</div>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=#{@maps_key}&libraries=places&callback=dispatchMapsEvent",
                            async: true,
                            defer: true,
                            "data-turbolinks-eval": false %>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">
  </head>

  <% if user_signed_in? %>
    <body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item">
                <a class="nav-link" href="<%= root_path %>">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span></a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="<%= events_path %>">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Eventos</span></a>
            </li>

            <li class="nav-item">
                <%= link_to '<i class="fas fa-fw fa-tachometer-alt"></i> <span>Editar perfil</span>'.html_safe, edit_user_registration_path, class: "nav-link" %>
            </li>

            <li class="nav-item">
                <%= link_to '<i class="fas fa-fw fa-tachometer-alt"></i> <span>Cerrar sesión</span>'.html_safe, destroy_user_session_path, :method => :delete, class: "nav-link" %>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

        </ul>
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Begin Page Content -->
                <div class="container-fluid">

                <%= yield %>

                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

        </div>
    </body>
  <% else %>
    <body>
        <%= yield %>
    </body>
  <% end %>
</html>